language: objective-c

# Travis default cocoapods install often lags behind what's necessary to access the specs repo. Update it first.
before_install:
    - gem update cocoapods --no-document
    - pod --version

env:
  matrix:
    - SDK=iphonesimulator7.0
    - SDK=iphonesimulator7.1
    #- SDK=iphonesimulator8.0

script:
    - xctool -workspace NovaCamera.xcworkspace -sdk $SDK -scheme NovaCamera build